package cn.kepu.elearning.pojo;

import java.sql.Timestamp;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;



/**
 * Eosoperator generated by MyEclipse Persistence Tools
 */
@XmlRootElement
public class Eosoperator implements java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -7747590100464253849L;

	private Integer operatorId;

	private String userId;

	private String password;

	private String operatorName;

	private String isLocal;

	private Integer status;

	private String userIdcode;
	
//验证密匙
	private String validataCode;
//	有效日期
	private Timestamp validDate;
	
// Employee 1v1 Operator
	private EosorgTEmployee eosorgTEmployee;
	
	/**
	 * 学员????????研究??????该字段不保存到数据库记录中，学员登陆后查询组织机构表获取该??后存储到operator内存对象??	 */
	private Integer tenantId;

	// Constructors

	/** default constructor */
	public Eosoperator() {
	}

	/** full constructor */
	public Eosoperator(String userId, String password, String operatorName,
			String isLocal, Integer status, String userIdcode) {
		this.userId = userId;
		this.password = password;
		this.operatorName = operatorName;
		this.isLocal = isLocal;
		this.status = status;
		this.userIdcode = userIdcode;
	}
	
	public Eosoperator(String userId, String password, String operatorName,
			String isLocal, Integer status, String userIdcode,String validataCode,Timestamp validDate) {
		this.userId = userId;
		this.password = password;
		this.operatorName = operatorName;
		this.isLocal = isLocal;
		this.status = status;
		this.userIdcode = userIdcode;
		this.validataCode = validataCode;
		this.validDate = validDate;
	}
	// Property accessors

	public Integer getOperatorId() {
		return this.operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getOperatorName() {
		return this.operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	public String getIsLocal() {
		return this.isLocal;
	}

	public void setIsLocal(String isLocal) {
		this.isLocal = isLocal;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getUserIdcode() {
		return this.userIdcode;
	}

	public void setUserIdcode(String userIdcode) {
		this.userIdcode = userIdcode;
	}
	@XmlTransient
	public EosorgTEmployee getEosorgTEmployee() {
		return eosorgTEmployee;
	}

	public void setEosorgTEmployee(EosorgTEmployee eosorgTEmployee) {
		this.eosorgTEmployee = eosorgTEmployee;
	}
	
	public Integer getTenantId() {
		return tenantId;
	}

	public void setTenantId(Integer tenantId) {
		this.tenantId = tenantId;
	}

	public String getValidataCode() {
		return validataCode;
	}

	public void setValidataCode(String validataCode) {
		this.validataCode = validataCode;
	}


	public void setValidDate(Timestamp validDate) {
		this.validDate = validDate;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((operatorId == null) ? 0 : operatorId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Eosoperator other = (Eosoperator) obj;
		if (operatorId == null) {
			if (other.operatorId != null)
				return false;
		} else if (!operatorId.equals(other.operatorId))
			return false;
		return true;
	}

}